### ISSUE TITLE
Fetch phone call history & recordings

### ISSUE THREAD

**Issue by Byunk** [KAIST-Google-Solution-Challenge/frontend#12]
## TODO
- [x] migrate to getx
- [x] fetch phone call history
- [x] fetch recording directories
- [x] fetch recording files
