### ISSUE TITLE
[Feature] Background Notification

### ISSUE THREAD

**Issue by Byunk** [KAIST-Google-Solution-Challenge/frontend#27]
## Details

현재까지의 테스트결과 세가지 문제점이 발생합니다.

1. apk 파일로 앱을 설치하는 경우 background service가 실행되지 않음.
2. Background service가 실행되는 경우에도 보이스 피싱이 탐지될 경우 푸시알림이 생성되지 않음.
3. Background에서 보이스 피싱이 탐지된 경우 바뀐 알림창이 원래대로 돌아오지 않음.

원활한 데모 비디오 영상 촬영을 위해선 2, 3 문제의 해결이 필요하고 1은 테스트 용으로는 handling이 필요하지만 데모비디오에 필수적이지 않습니다.

## Background

현재 background service는 다음의 요소로 구성되어 있습니다.

### Dependency

[`flutter_background_service`](https://pub.dev/packages/flutter_background_service)

[`flutter_local_notifications`](https://pub.dev/packages/flutter_local_notifications)

`main()`함수는 `BackgroundController()` 인스턴스를 생성하며, `init()` 메소드를 호출합니다.

```dart
Future<void> init() async {
    var permission = await requestPermission();
    if (permission) {
      _setCallStream(); // 실시간으로 Call status를 확인하는 stream channel
      _setSmsStream(); // 실시간으로 incoming sms를 확인하는 stream channel
      await _initBackService(); // Background service를 실행
    }
  }
```

각 stream 채널에서는 실시간으로 전화 / 문자를 감지하고 서버로 분석을 요청하여 결과를 반환하는 로직이 구성되어 있습니다. 현재까지 이부분에서 오류가 발생된 사례는 없습니다. **문제는 결과가 `Threshold` 이상일 경우에 두 stream channel은 `alertPhishing()`을 호출합니다.**

아래의 `alertPhishing()`은 알림창의 모습을 바꾸어주는 기능을 하고있으며 (초록색이던 알림이 빨간색으로 바뀜) 보이스피싱이 탐지될경우 '보이스 피싱이 감지되었습니다'라는 메시지를 알림창에 띄우는 역할을 합니다.

***<U>여기서 문제는 제가 이해한 바로는 이부분에서 푸시알림도 생성이 되어야 하는데, 푸시알림은 생성이 되지 않고 있습니다.</U>**

추가로 이부분의 코드에서 알림을 원래 모습대로 되돌릴 수 있을 것으로 예상합니다.

```dart
static void alertPhishing() {
    final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
        FlutterLocalNotificationsPlugin();
    flutterLocalNotificationsPlugin.show(
      888,
      notificationTitle,
      'Voice Phishing Detected!!!',
      const NotificationDetails(
        android: AndroidNotificationDetails(
          notificationTitle,
          'Voice Phishing Detected!!!',
          importance: Importance.max,
          priority: Priority.high,
          icon: 'ic_bg_service_small',
          color: Colors.red,
          ongoing: true,
          styleInformation: BigTextStyleInformation('보이스 피싱이 감지되었습니다!'),
          showWhen: true,
        ),
      ),
    );
  }
```

## TODO

- [x] : 백그라운드 로직 파악하기
- [x] : 바뀐 알림이 원래대로 돌아오도록 수정
- [x] : 푸시 알림 등의 시각적 효과 추가
- [x] : 시간적 여유가 생긴다면, apk 파일에서 백그라운드 실행이 안되는 이유 파악
